### ISSUE TITLE
Abstract is misleading

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/web-alarms#15]
The abstract reads: 

> This specification defines a system level API to provide access to the device alarm settings, which can schedule a notification or for an application to be started at a specific time. For example, some applications like alarm-clock, calendar or auto-update might need to utilize the Alarm API to trigger particular device behaviors at specified time points. 

Firstly, "system level API" doesn't mean much (or makes this API sound more special than it is). The system level API stuff relates this being an API that may only be accessible to privileged applications (i.e., packaged and digitally signed ones) ... or not. In any case, "system level" should be removed. 

Secondly, "provide access to the device alarm settings" is misleading. This makes it sound like the API gives you access "System Settings > Alarms", which is not the case. This part of the abstract should be removed. 

Thirdly, it says: "can schedule a notification". Notifications should be created with the Web Notifications API, not this API. 

Fourthly, calendar related tasks should be handed with the Calendar API. 

Fifthly, "for an application to be started at a specific time" makes it sound like this only works when applications are already closed. The case is that it generates a system message that is guaranteed to be delivered to the application at a given time (which may, consequently, involve activating the application by either starting it or otherwise putting it in the foreground).   

Sixthly, "trigger particular device behaviors" seems like a bit of overkill to justify the use case. I would make this more general: "perform some action" 

Seventhly, "time points" is tautological. 

This leaves me with:

> This specification defines an API to schedule the delivery of one or more system message to an application at a specified time. For example, applications like an alarm-clock or auto-update might need to utilize this API to perform some action at a specified time. 

Also, if applications are targeted through an alarm, do they really need to be focused? For example, if I'm playing a racing game, and an alarm goes off, it would be very annoying if I was taken out of my game to the other application... this would really annoy me if the developer had set this on their own, without me (as the user) having actually set the alarm. 

Real alarm clocks should only be settable at the system level, IMO (i.e., set only by the user). Cron jobs should maybe only target a Shared Worker and that worker should expose a .requestFocus(msg) method or something for requesting that the parent application be focused. In the UI, then, if I am playing a game or whatever, the System could notify me that 

``` ASCII
 +----------------------------------+
 +----------------------------------+
 | Application X requires your      |
 | attention: {msg}                 |
 |                                  |
 |                 [Open][Ignore]   |
 +----------------------------------+
```

**Comment by cdumez** [comment]
@marcoscaceres While I agree that the abstract needs rewriting, I think the proposal is a bit short. I would propose the following:

> This specification defines an API to schedule an alarm at a specified time. When the alarm goes off, the application that set the alarm will get notified via a system message. If the application is not running when the alarm is triggered, the system message will cause the application will be launched. Applications such as an alarm clock or an auto-updater may utilize this API to perform some action at a specified time.

What do you think?

**Comment by marcoscaceres** [comment]
Much better :)
