### ISSUE TITLE
Get review from W3C DOM WG about use of futures

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/web-alarms#29]
With the move to DOM's futures, we need to ensure that the text referring to futures has been spec'ed correctly. We should get a review from www-dom@w3.org.

**Comment by marcoscaceres** [comment]
Emailed www-dom: http://lists.w3.org/Archives/Public/www-dom/2013AprJun/0121.html

**Comment by marcoscaceres** [comment]
Talked to @annevk on IRC:

> you don't want "Call resolver's reject(value) method with error as value argument."; you want to call the internal resolve algorithm
> also needs to say something about running the remaining steps asynchronously and not terminating when you return
> looks okay otherwise

**Comment by cdumez** [comment]
"you don't want "Call resolver's reject(value) method with error as value argument."; you want to call the internal resolve algorithm" <- I don't understand this part. What is the internal resolve algorithm and what argument does it take?

The closest I could find in the DOM spec is "run resolver's resolve with value and the synchronous flag set."

**Comment by slightlyoff** [comment]
Why does this need to be synchronous? I don't understand why `reject(value)` is wrong for this use-case.

**Comment by annevk** [comment]
Because someone could have modified Resolver.prototype.reject so you want to invoke the internal algorithm. You don't need to set its synchronous flag though.
