### ISSUE TITLE
killing .clear()

### ISSUE THREAD

**Issue by marcoscaceres** [sysapps/web-alarms#39]
See:
http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/0433.html
http://lists.w3.org/Archives/Public/public-script-coord/2013AprJun/0431.html

**Comment by cdumez** [comment]
Same thing would apply to Contacts API then. To be consistent. 

However, I still think that clear() is much clearer than getPendingAlarms().then(alarms=>alarms.forEach(x=>x.cancel()));

**Comment by marcoscaceres** [comment]
heh, sure :)

**Comment by mounirlamouri** [comment]
.clear() is probably better than getPendingAlarms().then(alarms=>alarms.forEach(x=>x.cancel())); for performances...

**Comment by marcoscaceres** [comment]
ok, close this?

**Comment by mounirlamouri** [comment]
FWIW, I think Jonas' argument of no use case is quite valid. What do you guys think?

**Comment by marcoscaceres** [comment]
Yeah, I tend to agree. Jonas makes a good point.
