### ISSUE TITLE
Not clear whether alarms get persisted

### ISSUE THREAD

**Issue by Raynos** [sysapps/web-alarms#40]
- Does refreshing the web page clear the alarm automatically (like setTimeout gets cleared automatically)
- Does restarting the browser clear the alarm? (like sessionStorage)
- Does restarting the machine clear the alarm?

**Comment by cdumez** [comment]
I agree that it should be clearer. The spec does say: "All the alarms that have been added can be automatically restored after rebooting the system."

**Comment by Raynos** [comment]
I missed that statement!

**Comment by marcoscaceres** [comment]
@Raynos can we close?

**Comment by Raynos** [comment]
@marcoscaceres yes, however I feel this persisting across machine restarts should be made clear. It's the point that makes this API special.

**Comment by marcoscaceres** [comment]
@Raynos agreed. We will clear that up once we clear up the whole System Messages thing.
