### ISSUE TITLE
Alarm API should immediately fire alarms set in the 'past' rather than error.

### ISSUE THREAD

**Issue by airpingu** [sysapps/web-alarms#45]
Recently, we had a tiny change to redefine the our Mozilla Alarm API behaviour. Please see [1] for more details. In short, we thought it's meaningless to return an "InvalidStateError" error when adding an alarm in the past (the alarm API implementation has difficulty in determining what an "expired alarm" is due to the race condition issue). The content app should check the alarm's expiry before adding it. The system will always fire the alarm even if it's being added as expired by Alarm API.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=876936

Gene

**Comment by marcoscaceres** [comment]
This change makes sense to me. It's also interesting to see that Android does the same (as reported in the linked bug).

**Comment by cdumez** [comment]
Makes sense to me as well.
