### ISSUE TITLE
ScheduledTask - timezone identifier values

### ISSUE THREAD

**Issue by martap** [sysapps/web-alarms#46]
IDEA:
Marcos Caceres, Anne van Kesteren and Mounir Lanouri proposed ScheduleTask object like:

``` js
[Constructor (Date date, DOMString timezone, any data] interface ScheduledTask {
  readonly attribute DOMString id;
  readonly attribute Date      date;
  readonly attribute DOMString timezone;
  readonly attribute any       data;
};
```

where:

```
{timezone: timezone | none | current }  
```

PROBLEM: 
Find best possible names for timezone identifier (aka old ignoreTimezone/respectTimezone)

BACKGROUND OF THE PROBLEM:

I did some experiment and I asked few coworkers + few my friends (10 people from different teams and companies) what they understand when using timezone: "none", "ignoreTimeZone", "noTimeZone" and "current". 

My conclusions:
-  "ignore..." is bad word - this is totally misunderstood (only one person understand it correctly)
- "none" is not intuitive for most of people as they can't understand why to use none in case of TimeZone and how it suppose to work, this is confusing word.
-  "current" - current is understood as old meaning of "ignoreTimeZone", so misunderstanding again

What propositions I got was to use instead of "none" (spec ignoreTimeZone meaning):
-  update (which is confusing as Mounir mentioned previously)
-  any (10% propositions)
-  auto (70% propositions)
-  local (20% propositions)

I believe "current" and "none" might be misunderstood as in case of "ignore" and "respect" (at least from my experiment). However I'm not satisfy with any of proposed names...

DISCUSSION ON THE LIST:
_[Alarm API: ignoreTimezone/respectTimezone](http://lists.w3.org/Archives/Public/public-sysapps/2013Jun/0007.html)_

**Comment by marcoscaceres** [comment]
Reformatted issue description with a bit of markdown.

**Comment by martap** [comment]
Thanks  :)

**Comment by cdumez** [comment]
Do we really need to be able to specify an timezone identifier? I think this will make implementation more complex. The most common use cases are to use the system's current timezone or no timezone at all.

For calendar alarms, I do see the need to specify a timezone identifier. However, calendar alarms are out of scope. cron, AFAIK, uses the system's timezone and that's it.

I do agree that respectTimezone / ignoreTimezone are a bit confusing. My personal preference would be (in a dictionary):
boolean synchronizeWithSystemTimezone = true;
or
boolean followSystemTimezone = true;

This is basically the difference, in one case we use the current system timezone and ignore later system timezone changes. In the other, we keep the Task timezone synchronized with the system's timezone in case of changes.

**Comment by marcoscaceres** [comment]
If calendar alarms are out of scope, then what @cdumez is proposing would be sufficient (_cough_ useSystemTimezone _cough_). However, let's get agreement during the f2f that cal alarms are out of scope - and make sure the spec says so (if it does not already).

**Comment by cdumez** [comment]
I thought this was agreed earlier. If not, I don't mind supporting calendar use cases.
In that case, I would fully support adding a timezone identifier to ScheduledTask.

**Comment by marcoscaceres** [comment]
I don't think it was (at least that's never been clear to me as people keep telling me that we don't need a calendar API because we have this API! :smiley_cat: ). It's also the reason we made the proposal for explicit timezones in the first place.

**Comment by cdumez** [comment]
Is there anything else (besides proper timezone support) missing to support calendar alarm use cases? Nothing else comes to mind as the associated Object data can be used to store things like a description / summary, action (AUDIO, DISPLAY, EMAIL).

Calendar alarms can usually be specified as repeating but nothing prevents the API user from scheduling several tasks in the task scheduler for a single calendar alarm (or rescheduling a task if the previous alarm was snoozed).

If timezone is the only thing missing, then I think we might just as well support it in Task Scheduler.

ical's VALARM: http://www.kanzaki.com/docs/ical/valarm.html

**Comment by marcoscaceres** [comment]
How would an app know if a task was snoozed?

**Comment by cdumez** [comment]
Well, the task only starts/notifies the application. It is the application that is in charge of displaying the alarm notification, therefore, the application will know if the alarm was snoozed (e.g. the snoozed button was pushed). If the snooze button was pushed, the application can schedule another task.

**Comment by martap** [comment]
Even though I personally do not like idea of removing timezone. Most of us agreed on F2F meeting that TaskScheduler wont' use it at all. 

Based on that closing this issue.

**Comment by martap** [comment]
BTW I liked idea to use "follow" word in the name - it was not perfect but very close to perfect :)

**Comment by mounirlamouri** [comment]
We should label this issue as for "LATER" because it is something we might be interested to add later to improve the specification.

**Comment by marcoscaceres** [comment]
Added LATER tag.
