### ISSUE TITLE
Dead link to the Latest editor's draft

### ISSUE THREAD

**Issue by AurelioDeRosa** [sysapps/web-alarms#64]
In the [Working Draft published](http://www.w3.org/TR/web-alarms/), the Latest editor's draft points to a page that doesn't exist anymore (http://sysapps.github.io/sysapps/proposals/alarm/Overview.html).

**Comment by cdumez** [comment]
@marcoscaceres could you advise how to fix this? Maybe we should republish a more recent draft?

**Comment by marcoscaceres** [comment]
@cdumez sorry for the delay, we can just create an Overview.html file with a: 

```
<meta http-equiv="refresh" content='0;URL="http://www.w3.org/2012/sysapps/web-alarms/"'>  
```

**Comment by marcoscaceres** [comment]
(updated comment above)

**Comment by AurelioDeRosa** [comment]
This issue has been fixed.
